dataset: 'tumrgbd'
meshing:
  resolution: 0.01 # Increase this number to speed up meshing algorithm
  eval_rec: False
tracking:
  ignore_edge_W: 20
  ignore_edge_H: 20
  lr_T: 0.01
  lr_R: 0.002
  pixels: 5000
  iters: 200
mapping:
  every_frame: 1
  keyframe_every: 1
  pixels: 5000
  iters: 60
cam:  #NOTE: intrinsic is different per scene in TUM
  H: 480
  W: 640
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  png_depth_scale: 5000.0
  crop_edge: 0
rendering:
  n_stratified: 48
  n_importance: 8
  learnable_beta: False