inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-6.0,1.8],[-3.6,3.3],[-2.0,1.9]]
  marching_cubes_bound: [[-6.0,1.8],[-3.6,3.3],[-2.0,1.9]]
data:
  input_folder: Datasets/Replica/room1
  output: output/Replica/room1