inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-3.3,8.5],[-5.7,4.2],[-5.4,3.2]]
  marching_cubes_bound: [[-3.3,8.5],[-5.7,4.2],[-5.4,3.2]]
data:
  input_folder: Datasets/Replica/room2
  output: output/Replica/room2